name: Generate Snake

on:
  schedule: # runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # allows you to run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: PREM015
          outputs: |
            dist/snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}