name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: PREM015
          outputs: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generated snake animation"
          add: "dist/snake.svg"